### ISSUE TITLE
No video files! All folders are empty

### ISSUE THREAD

**Issue by aicynide** [JDRIVO/gDrive#1]

**Comment by JDRIVO** [comment]
By design, when you sync a folder, STRM files corresponding to your video files will be created. You can then browse your library as if it were stored locally.

**Comment by aicynide** [comment]
I'm in many Shared Drives so can you add feature to play video withinghe add-on only? Or serve a webdav/ftp server

**Comment by JDRIVO** [comment]
This addon performs your request.

https://github.com/cguZZman/plugin.googledrive
