### ISSUE TITLE
Add Instructions for Usage

### ISSUE THREAD

**Issue by aicynide** [JDRIVO/gDrive#4]

**Comment by JDRIVO** [comment]
What part of the addon do you need assistance with? I was thinking of adding a video outlining how to create Client ID as I think that's the only hurdle uninformed users would have to overcome.

**Comment by aicynide** [comment]
How fast is it compared to Google Drive add-on?

**Comment by JDRIVO** [comment]
If you are referring to how quickly STRM files are created, that depends on the number of threads you choose.
