### ISSUE TITLE
Files are missing 

### ISSUE THREAD

**Issue by kiran-venugopal** [JDRIVO/gDrive#7]
Successfully added oauth client and secret but still files are missing and only one empty folder is added

![Screenshot 2024-06-02 223233](https://github.com/JDRIVO/gDrive/assets/62516337/34c5058b-c951-43b3-8c20-9c3813e9d2b2)
![Screenshot 2024-06-02 223303](https://github.com/JDRIVO/gDrive/assets/62516337/8b661816-00f6-4a75-9d62-a6d6312c911e)

**Comment by JDRIVO** [comment]
Could you uninstall the addon and remove its data and then download/install the master build?
